require: rubocop-rspec

Metrics/LineLength:
  Max: 200

Documentation:
    Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/models/repo_data_spec.rb' # main describe block too big :(
    - 'spec/models/github_client_spec.rb' # main describe block too big :(
    - 'spec/features/repositories_table_spec.rb' # too man expects :(
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true
