require: rubocop-rspec

Metrics/LineLength:
  Max: 200

Documentation:
    Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/Lambda:
  Enabled: false
